#!/bin/sh
for i in 01 02 03 04 06 07 08 09 10 11 
do
	echo
	echo ======================== Starting service on hec-$i
	ssh hec-$i 'nfs/fusionFS/start_service </dev/null >/dev/null; ps | grep -e ffsnetd -e server_zht' 
done
